CONFIG_IMAGES_DIR = "./Images/";
CONFIG_SCENES_DIR = "./Scenes/";
CONFIG_LIBRARY_FILES_DIR = "./LibraryFiles/";
CONFIG_CHARS_DIR = "./Chars/";
CONFIG_PLANTS_DIR = "./Plants/";
CONFIG_HOUSES_DIR = "./Houses/";
CONFIG_OTHERS_DIR = "./Others/";

///////////////////////////
// DO NOT MODIFY
///////////////////////////
CONFIG_STAGES_PATH = CONFIG_IMAGES_DIR + CONFIG_SCENES_DIR;
CONFIG_CHARS_PATH = CONFIG_IMAGES_DIR + CONFIG_CHARS_DIR;
CONFIG_PLANTS_PATH = CONFIG_IMAGES_DIR + CONFIG_PLANTS_DIR;
CONFIG_HOUSES_PATH = CONFIG_IMAGES_DIR + CONFIG_HOUSES_DIR;
CONFIG_OTHERS_PATH = CONFIG_IMAGES_DIR + CONFIG_OTHERS_DIR;
CONFIG_LOGGING_VERBOSE = false;